name: JAVA Selenium CI Pipeline 

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
      - name: Prepare rerun.txt
        shell: pwsh
        run: |
              New-Item -ItemType Directory -Path target -Force
              New-Item -ItemType File -Path target\rerun.txt -Force
    

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Run tests
        run: mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/target/surefire-reports
            **/target/failsafe-reports

      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            **/*.log

      - name: Post a comment (optional)
        if: ${{ failure() }}
        run: echo "Build or tests failed. Check reports."
